### ISSUE TITLE
Error reading from database

### ISSUE THREAD

**Issue by Dodo212** [catalyst/moodle-tool_webanalytics#11]
Hi My Moodle error when installing this plug in. The error message just this sentence "Error reading from database". No other message.

Moodle 3.4 (Build: 20171113)

Item | Detail
-- | --
cPanel Versi | 70.0 (build 42)
Versi Apache | 2.4.33
Versi PHP | 5.6.36
Versi MySQL | 5.6.39
Arsitektur | x86_64
Sistem Operasi | linux
Jalur ke Sendmail | /usr/sbin/sendmail
Jalur ke Perl | /usr/bin/perl
Versi Perl | 5.10.1
Versi Kernel | 2.6.32-896.16.1.lve1.4.53.el6.x86_64

Server basis data
    Server: Localhost via UNIX socket
    Jenis server: MySQL
    Versi server: 5.6.39-log - MySQL Community Server (GPL)
    Versi protokol: 10
    Pengguna: cpses_brvijfkp7m@localhost
    Kumpulan karakter server: UTF-8 Unicode (utf8)

Server web
    cpsrvd 11.70.0.42
    Versi klien basis data: libmysql - 5.1.73
    Ekstensi PHP: mysqliDokumentasi curlDokumentasi mbstringDokumentasi
    Versi PHP: 5.6.30

phpMyAdmin
    Informasi versi: 4.7.7 

Activity modules
--

Plugin name | Version | Availability | Actions | Notes
-- | -- | -- | -- | --
Accredible certificates & badgesmod_accredible | v1.4.132018060601 | Enabled | Settings | Uninstall | Additional
BigBlueButtonBNmod_bigbluebuttonbn | 2.2.42017101012 | Enabled | Settings | Uninstall | Additional
Custom certificatemod_customcert | 3.4.32017111303 | Enabled | Settings | Uninstall | Additional
Gamemod_game | 2017-08-142017081401 | Enabled | Settings | Uninstall | Additional
H5Pmod_hvp | 1.92018053100 | Enabled | Settings | Uninstall | Additional
Offline Quizmod_offlinequiz | v3.4.22018011602 | Enabled | Settings | Uninstall | Additional
Questionnairemod_questionnaire | 3.4.2 (Build - 2018061900)2017111104 | Enabled | Settings | Uninstall | Additional
Quizventuremod_quizgame | v3.5-r12018042900 | Enabled |   | Uninstall | Additional
Realtime quizmod_realtimequiz | 3.4+ (Build: 2018042100)2018042100 | Enabled | Settings | Uninstall | Additional
StudentQuizmod_studentquiz | v3.0.32018051300 | Enabled | Settings | Uninstall | Additional
360° feedbackmod_threesixo | v3.4-r42017081603 | Enabled |   | Uninstall | AdditionalThere is a new version 2017081604 available!Release v34.1.0 Stable version Download More info...
Treasure Huntmod_treasurehunt | v1.2.162018031900 | Enabled | Settings | Uninstall | Additional
Background imagecustomcertelement_bgimage | 2017111300 |   |   |   | Additional
Bordercustomcertelement_border | 2017111300 |   |   |   | Additional
Category namecustomcertelement_categoryname | 2017111300 |   |   |   | Additional
Codecustomcertelement_code | 2017111300 |   |   |   | Additional
Course namecustomcertelement_coursename | 2017111300 |   |   |   | Additional
Datecustomcertelement_date | 2017111300 |   |   |   | Additional
Digital signaturecustomcertelement_digitalsignature | 2017111300 |   |   |   | Additional
Gradecustomcertelement_grade | 2017111300 |   |   |   | Additional
Grade item namecustomcertelement_gradeitemname | 2017111300 |   |   |   | Additional
Imagecustomcertelement_image | 2017111300 |   |   |   | Additional
Student namecustomcertelement_studentname | 2017111300 |   |   |   | Additional
Teacher namecustomcertelement_teachername | 2017111300 |   |   |   | Additional
Textcustomcertelement_text | 2017111300 |   |   |   | Additional
User fieldcustomcertelement_userfield | 2017111300 |   |   |   | Additional
User picturecustomcertelement_userpicture | 2017111300 |   |   |   | Additional
Offlinequiz Results Overviewofflinequiz_overview | 2015092500 |   |   | Uninstall | Additional
Offlinequiz Regradingofflinequiz_regrade | 2015092500 |   |   | Uninstall | Additional
Offlinequiz Results Importofflinequiz_rimport | 2015092501 |   |   | Uninstall | Additional
Offline Quiz Statisticsofflinequiz_statistics | 2015092500 |   |   | Uninstall | Additional
Safe Exam Browser quiz access rulequizaccess_safeexambrowser | 1.2 for Moodle 3.2+2018021600 |   |   | Uninstall | Additional
Comparison with the weightiest assessmentworkshopeval_weightiest | 1.22017112200 |   |   | Uninstall | Additional
Advanced notificationsblock_advnotifications | v1.2.12018042716 | Enabled | Settings | Uninstall | Additional
Analytics Graphsblock_analytics_graphs | v4.0.42018012501 | Enabled |   | Uninstall | Additional
Course Checks Blockblock_bcu_course_checks | 1.3.12018031401 | Enabled | Settings | Uninstall | Additional
Featured Coursesblock_featuredcourses | 52018050200 | Enabled |   | Uninstall | Additional
Pollblock_poll | 3.3.0.02018052500 | Enabled | Settings | Uninstall | Additional
Theme selectorblock_theme_selector | 2.9.1.42015082106 | Enabled | Settings | Uninstall | Additional
Level up!block_xp | 3.2.12018050900 | Enabled | Settings | Uninstall | Additional
Multi-Embed Filterfilter_multiembed | 3.52018051301 | Disabled | Settings | Uninstall | Additional
Correctionsatto_corrections | 1.0.7 for Moodle 2.7-3.5 (Build 2018050201)2018050201 |   | Settings | Uninstall | Additional
Anti-hammering / Login blockerauth_antihammer | 3.3.0 (build 2017092501)2017092501 | Disabled | Settings | Uninstall | Additional
Opcache managementtool_opcache | v3.4-r32018051700 | Enabled |   | Uninstall | Additional
User Suspensiontool_usersuspension | 3.3.0 (build 2017092500)2017092500 | Enabled |   | Uninstall | Additional
eTask topics formatformat_etask | 3.3.1 (Moodle 2.9)2018052300 | Enabled | Settings | Uninstall | Additional
My feedbackreport_myfeedback | 2.14 (Build: 2018052900)2018052900 |   |   | Uninstall | Additional
Rosterreport_roster | v3.4.02018051300 |   |   | Uninstall | Additional
Grade distributiongradereport_gradedist | v3.4.02017103000 |   |   | Uninstall | Additional
Course templateslocal_course_templates | Course templates plugin Version 3.5-b2018061400 |   |   | Uninstall | Additional
Maintenance mode (live check)local_maintenance_livecheck | v3.4-r22018051700 |   |   | Uninstall | Additional
Moodle Mobile additional featureslocal_mobile | 3.4.3502017111302 |   |   | Uninstall | Additional
Sandboxlocal_sandbox | v3.4-r42018051700 |   |   | Uninstall | Additional

**Comment by danmarsden** [comment]
Hi there, 

can you please set the debugging level in your site to "developer" with "display errors" set to on and then provide the full error message that appears?

thanks,

**Comment by Dodo212** [comment]
Hi there,
When I am installing

Debugging output enabled
Downloading tool_webanalytics ... 
 <- https://moodle.org/plugins/download.php/17191/tool_webanalytics_moodle35_2018062400.zip
 -> /home/brisyari/moodledata/temp/core_plugin/code_manager/distfiles/c3daa65c9c7b7f5d72f7023d931efe86.zip ... OK
Validating tool_webanalytics ... OK
  [OK] Name of the plugin to be installed [webanalytics] 
    Help with Name of the plugin to be installed

 
  [OK] Plugin version [2018062400] 
  [OK] Required Moodle version [2017051500] 
  [OK] Full component name [tool_webanalytics] 
  [OK] Declared maturity level [MATURITY_STABLE] 
    Help with Declared maturity level

 
  [OK] Plugin release [2018062400] 
  [Debug] Found language file [tool_webanalytics] 
  [OK] Write access check [/home/brisyari/public_html/admin/tool] 

Validation successful, installation can continue

-------------------------------------------------------------------------
When error happened

 Table "tool_webanalytics" does not exist


Debug info:
Error code: ddltablenotexist
Stack trace:

    line 665 of /lib/dml/moodle_database.php: dml_exception thrown
    line 1350 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
    line 193 of /admin/tool/webanalytics/classes/records_manager.php: call to moodle_database->get_records()
    line 141 of /admin/tool/webanalytics/classes/records_manager.php: call to tool_webanalytics\records_manager->get_multiple()
    line 53 of /admin/tool/webanalytics/classes/injector.php: call to tool_webanalytics\records_manager->get_enabled()
    line 34 of /admin/tool/webanalytics/lib.php: call to tool_webanalytics\injector::inject()
    line 1160 of /lib/outputrenderers.php: call to tool_webanalytics_before_http_headers()
    line 437 of /lib/outputrenderers.php: call to core_renderer->header()
    line 208 of /admin/renderer.php: call to plugin_renderer_base->__call()
    line 679 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

----------------------------------------------------------------------------
When I renamed the folder using cPanel file manager, so my web go live again.

Plugins check
Cancelling installation of plugins
The following plugins are not fully installed yet so their installation may be cancelled. To do so, the plugin folder must be removed from the server now. Make sure this is really what you want to prevent accidental data loss (such as your own code modifications).
[pluginname,tool_webanalyticss] (tool_webanalyticss)
Folder to be deleted: /home/brisyari/public_html/admin/tool/webanalyticss

**Comment by dmitriim** [comment]
@Dodo212 thank you for the additional info about this issue. 

I'm still struggling to replicate the issue. I was able to install the plugin using CLI and web interface. 

One thing I noticed is that you user PHP 5.6.36 with Moodle 3.4, when the minimum version required is PHP 7.0.0 See https://docs.moodle.org/dev/Moodle_3.4_release_notes 

Do you have any core customisation in your instance which could cause this issue?

**Comment by danmarsden** [comment]
sounds like tool_webanalytics\injector::inject() is being triggered before the install/upgrade (on the upgrade_plugin_check_page)  maybe we should add a check to see if tool_webanalytics has been installed inside the inject() function?

**Comment by dmitriim** [comment]
@danmarsden you are right, but I'm still struggling to replicate it :) will add required checks once get the same error...

**Comment by dmitriim** [comment]
@Dodo212 could you please let me know how did you installed the plugin? Did you use "Install plugins from the Moodle plugins directory" button?

**Comment by Dodo212** [comment]
@dmitriim maybe i should update PHP. I'm not sure any customisation cause this issue because I can still install another plug in.

Yes I installed it from website Moodle plugins directory. Not from upload file.

**Comment by RekhaC** [comment]
I also got Error reading database and the site went blank till i deleted the plugin via FTP from admin/tool. 
See attached screenshot of Debugging ERrors
![screen shot 2018-07-24 at 11 39 20 pm](https://user-images.githubusercontent.com/16319899/43157774-9726712a-8f9b-11e8-9685-68aa956d6ebe.png)

Moodle 3.4 (Build: 20171113)

Is there any other way to put a conversion/ Pixel tracking code on sign-up confirmation pages?

**Comment by dmitriim** [comment]
@RekhaC  thanks for reporting this. I'm still struggling to replicate this error. Could you please describe exact steps you have done?

**Comment by fishfree** [comment]
I have the same problem.

**Comment by dmitriim** [comment]
@fishfree  can you please provide exact steps to replicate?

**Comment by fishfree** [comment]
@dmitriim I have nearly the same environment as that of Dodo212. Maybe you could consider danmarsden's suggestion first and make some modifications, then we can retry. :-)

**Comment by dmitriim** [comment]
@fishfree the pull requests are always appreciated!

**Comment by fishfree** [comment]
@dmitriim Sorry, I'm not familiar with Moodle programming.

**Comment by dmitriim** [comment]
I have pushed the patch to check if table exists before injecting the code. This should fix the issue,

**Comment by fishfree** [comment]
@danmarsden It works now. Thank you!

**Comment by dmitriim** [comment]
@fishfree I fixed it! Why "thank you" to @danmarsden??!! Haha :)
