### ISSUE TITLE
How to view matomo in moodle page itself?

### ISSUE THREAD

**Issue by Priya1950** [catalyst/moodle-tool_webanalytics#17]
Hi,
I installed matomo in my local server. How to view the matomo dashboard in moodle page itself apart from new window?

**Comment by dmitriim** [comment]
HI @Priya1950!

Not sure what you are trying to achieve, but the plugin doesn't show any dashboards. It renders required Matomo JS code to be able to track users and send info to your Matomo server. All you need to know is Matomo URL and site ID. Please see documentation https://github.com/catalyst/moodle-tool_webanalytics/blob/master/README.md to understand how the plugin works.

Cheers,
Dmitrii
