### ISSUE TITLE
Embed videos (YouTube) are not playing correctly when Matomo enabled

### ISSUE THREAD

**Issue by yao9394** [catalyst/moodle-tool_webanalytics#20]
Hi, 

One of our client had this issue that Embed videos (YouTube) are not playing correctly when Matomo enabled. When the play button is clicked, only audio is playing. Have found that there are some lines of code in https://www.catalyst-analytics.nz/piwik.js changing attributes for Youtube iframe. If we search for string "enablejsapi", we could see the js set this attribute for Youtube iframe tags. And we could not find the same lines in this version of piwik.js https://analytics.catalyst-au.net/piwik.js. Not sure if this is the root cause. But as long as Matomo is disabled, all YouTube videos on the site playing correctly.  Thus, as Brendan suggested, create a setting that allows other version of piwik.js, if leave the setting empty, the original version will still apply. 

#19 

Thanks

John Y

**Comment by dmitriim** [comment]
Fixed as part of #19
