### ISSUE TITLE
Error reading from database

### ISSUE THREAD

**Issue by agogo123** [catalyst/moodle-tool_webanalytics#22]
Hello,

I've recently downloaded this tool and found myself stuck with the error "Scheduled task failed: Link crawler robot (tool_crawler\task\crawl_task),Error reading from database".  My environment runs moodle on Windows Server 2012 R2 with the database server being SQL Server 2012 R2.

I've put my moodle into developer debugger mode and found that there is a SQL error that is specific to SQL Server.

Here is the information:
Link crawler robot
Execute scheduled task: Link crawler robot (tool_crawler\task\crawl_task)
... started 15:05:27. Current memory use 6.4MB.
... used 3 dbqueries
... used 0.057562828063965 seconds
Scheduled task failed: Link crawler robot (tool_crawler\task\crawl_task),Error reading from database
Debug info:
SQLState: 42000<br>
Error Code: 102<br>
**Message: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near 'LIMIT'.<br>**

SELECT *
                                         FROM mdl_tool_crawler_url
                                        WHERE lastcrawled IS NULL
                                           OR lastcrawled < needscrawl
                                     ORDER BY needscrawl ASC, id ASC
                                        LIMIT 1
                                    
[array (
)]
Backtrace:
* line 324 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
* line 431 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
* line 896 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
* line 972 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
* line 1571 of \lib\dml\moodle_database.php: call to sqlsrv_native_moodle_database->get_records_sql()
* line 485 of \admin\tool\crawler\classes\robot\crawler.php: call to moodle_database->get_record_sql()
* line 102 of \admin\tool\crawler\lib.php: call to tool_crawler\robot\crawler->process_queue()
* line 52 of \admin\tool\crawler\classes\task\crawl_task.php: call to tool_crawler_crawl()
* line 105 of \lib\cronlib.php: call to tool_crawler\task\crawl_task->execute()
* line 297 of \lib\cronlib.php: call to cron_run_inner_scheduled_task()
* line 91 of \admin\tool\task\schedule_task.php: call to cron_run_single_task()

For SQL Server, the SQL should be:

SELECT top 1 *
                                         FROM mdl_tool_crawler_url
                                        WHERE lastcrawled IS NULL
                                           OR lastcrawled < needscrawl
                                     ORDER BY needscrawl ASC, id ASC

**Comment by dmitriim** [comment]
Seems like you messed with the plugin @agogo123  Please log your bug in https://github.com/catalyst/moodle-tool_crawler

**Comment by agogo123** [comment]
dmitriim, I didn't play around with the plugin.  I looked into the code to understand why it wasn't working for me.  Has this plugin ever worked with a SQL Server DB?
