### ISSUE TITLE
Use of subplugins.php has been deprecated.

### ISSUE THREAD

**Issue by AdrianoRuseler** [catalyst/moodle-tool_webanalytics#24]
Use of subplugins.php has been deprecated. Please update your '/var/www/html/moodle38/admin/tool/webanalytics' plugin to provide a subplugins.json file instead.
!!! Exception - syntax error, unexpected '.1' (T_DNUMBER) !!!

**Comment by dmitriim** [comment]
Hey @AdrianoRuseler 
The plugin hasn't been tested on Moodle 3.8+, so officially it doesn't support this version.

"syntax error" in an interesting one. Can you please provide full stack of this error (you can get it with full debugging on)? Also would be good to know moodle version, PHP version and the plugin version.

Thank you!

**Comment by AdrianoRuseler** [comment]
Hey @dmitriim 
Thanks for the reply.

I found out that this bug (already fixed) is related to another plugin (moodle-atto_fullscreen), so don't worry. 

Sorry for bothering you!
