### ISSUE TITLE
tidy up privacy lang.

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_webanalytics#4]
$string['privacy:metadata'] = 'Web Analytics Tool only provides a way for subplugins to store their settings and display JS code.';

might read better like:

$string['privacy:metadata'] = The 'Web Analytics plugin does not store any personal data, however sub-plugins implement their own privacy policies.';

**Comment by dmitriim** [comment]
Fixed it in https://github.com/catalyst/moodle-tool_webanalytics/pull/3
